version: "3"

services:

  postgres:
    image: kartoza/postgis:12.4
    environment:
      POSTGRES_PASS: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DBNAME: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432

